export const vaccins = [
  {
    nom: 'BBIBP-CorV',
    inventeurs: ['Sinopharm'],
    lieudeproduction: ['Chine'],
    technologie: 'virus inactivé',
    quantite: 420,
    prixunitaire: 17,
    approuve: true,
    image: 'bbibp-corv.jpg',
  },

  {
    nom: 'Sputnik V',
    inventeurs: ['Gamaleya'],
    lieudeproduction: ['Russie', 'Inde'],
    technologie: 'adenovirus',
    quantite: 130,
    prixunitaire: 12,
    approuve: false,
    image: 'sputnik-v.jpg',
  },
  {
    nom: 'AZD1222',
    inventeurs: ['AstraZeneca', 'University of Oxford'],
    lieudeproduction: ['Royaume Unis', 'Brésil', 'Inde'],
    technologie: 'adenovirus',
    quantite: 5028,
    prixunitaire: 1.78,
    approuve: false,
    image: 'azd1222.jpg',
  },

  {
    nom: 'Tozinameran',
    inventeurs: ['BioNTech', 'Pfizer', 'Fosun Pharma'],
    lieudeproduction: ['Allemagne', 'USA'],
    technologie: 'ARN messager',
    quantite: 980,
    prixunitaire: 14,
    approuve: true,
    image: 'tozinameran.jpg',
  },

  {
    nom: 'mRNA-1273',
    inventeurs: ['Moderna', 'NIAID', 'BARDA'],
    lieudeproduction: ['USA'],
    technologie: 'ARN messager',
    quantite: 240,
    prixunitaire: 28,
    approuve: false,
    image: 'mrna-1273.jpg',
  },
  {
    nom: 'Ad26.COV2.S',
    inventeurs: ['Johnson & Johnson', 'BIDMC'],
    lieudeproduction: ['USA', 'Amérique du Sud', 'Ukraine', 'Afrique du Sud'],
    technologie: 'adenovirus',
    quantite: 110,
    prixunitaire: 31,
    approuve: false,
    image: 'ad26-cov2-s.jpg',
  },

];
